# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: AzureResourceManagerTemplateDeployment@3
  inputs:
    deploymentScope: 'Subscription'
    azureResourceManagerConnection: 'Free Trial(52bc4dc8-a26d-473e-9544-fcb5f04bf270)'
    subscriptionId: '52bc4dc8-a26d-473e-9544-fcb5f04bf270'
    location: 'UK South'
    templateLocation: 'Linked artifact'
    csmFile: 'https://github.com/Azure/azure-quickstart-templates/blob/master/101-key-vault-create/azuredeploy.json'
    csmParametersFile: 'https://github.com/Azure/azure-quickstart-templates/blob/master/101-key-vault-create/azuredeploy.parameters.json'
    deploymentMode: 'Incremental'